### ISSUE TITLE
Assignment0-ifs.cpp-Is there a need to clamp in the end?

### ISSUE THREAD

**Issue by PeterHUistyping** [Birdy-C/MIT-6-837#3]
Given that _"Be careful --- do not try to edit values outside the bounds of the image. "_
I suppose that the values outside the image should be thrown away instead. 
Not pretty sure about it.

**Comment by Birdy-C** [comment]
Yeah they should be thrown away, which means we don't care about the color of the pixel outside the image.
On image.h, 
```
assert(x >= 0 && x < width);
assert(y >= 0 && y < height);
```
will give you error if you edit the image outside of bounds.

**Comment by PeterHUistyping** [comment]
Yeah, however, I suppose that on ifs.cpp,
 `tx = max(tx, 0);
 ty = max(ty, 0);`
could add pixel outside the image.

Especially when outputting dragon.tga, the input parameters exceed the image. 
<img width="396" alt="Dragon" src="https://user-images.githubusercontent.com/100888245/183274950-fb183510-bd78-4010-90eb-d52f9112791d.png">

**Comment by PeterHUistyping** [comment]
> Yeah, however, I suppose that on ifs.cpp, `tx = max(tx, 0); ty = max(ty, 0);` could add pixel outside the image.
> 
> Especially when outputting dragon.tga, the input parameters exceed the image. <img alt="Dragon" width="396" src="https://user-images.githubusercontent.com/100888245/183274950-fb183510-bd78-4010-90eb-d52f9112791d.png">

Thanks for reply!
In addition, I don't know why this particular one exceeds the boundary of the image.

**Comment by Birdy-C** [comment]
Oh, you are right, I believe that's a mistake I left in the code. dragon.tga may be the only one testing the pixel outside boundary case I guess?
Thanks for updating! I'll leave a TODO in code and update it later.
